language: perl

perl:
    - "5.14"
    - "5.24"
    - "5.26"

install:
    - cpanm -qn --installdeps .
    - cpanm -qn --skip-satisfied Devel::Cover::Report::Codecov
    - cpanm -qn --skip-satisfied Devel::Cover::Report::Coveralls

after_success:
    - cover -test
    - cover -report codecov
    - cover -report coveralls

notifications:
    recipients:
        - mirko@westermeier.de
    email:
        on_success: always
        on_failure: always
